### ISSUE TITLE
Cannot fetch file error when clicking on import

### ISSUE THREAD

**Issue by bastians** [xperseguers/t3ext-sphinx#2]
I installed the latest version of the extension from Github and when I try to import a version, I get the following error:

> Cannot fetch file https://github.comhttps://api.github.com/repos/sphinx-doc/sphinx/zipball/v1.8.1.

It seems, that the URL is wrong.

TYPO3 7.6.31
Extension 2.5.1 (latest version from Github repo with the changes that are not published in the TER yet)

Btw: With the version from the TER, I always get an OpenSLL error but everything is installed correctly.

**Comment by bastians** [comment]
@xperseguers Did you already have a chance to look into this issue?

**Comment by xperseguers** [comment]
unfortunately not :(

**Comment by xperseguers** [comment]
Currently facing a disk problem locally so cannot test it completely my patch.

**Comment by bastians** [comment]
Yeah, works. I get another error now, but I guess this is related to my server: 

> Could not extract Sphinx v1.8.0.

**Comment by xperseguers** [comment]
Please see amended commit and possibly #5
